# Generated by Django 4.1.6 on 2023-02-10 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Uzduotis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200, verbose_name='Pavadinimas')),
                ('text', models.CharField(help_text='Įveskite užduotį (jos informaciją)', max_length=200, verbose_name='Tekstas')),
                ('data', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Iki')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Užduotis',
                'verbose_name_plural': 'UŽduotys',
                'ordering': ['-data'],
            },
        ),
    ]
